"""Описание изменений

Revision ID: 680b32af9292
Revises: 
Create Date: 2024-09-22 10:58:42.964607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '680b32af9292'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_products')
    op.create_unique_constraint(None, 'categories', ['slug'])
    op.create_unique_constraint(None, 'deliveries', ['slug'])
    op.add_column('orders', sa.Column('product_slug', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('delivery_category', sa.String(), nullable=True))
    op.alter_column('orders', 'delivery_person',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'orders', ['slug'])
    op.drop_constraint('orders_delivery_slug_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'products', ['product_slug'], ['slug'])
    op.create_foreign_key(None, 'orders', 'deliveries', ['delivery_person'], ['slug'])
    op.drop_column('orders', 'delivery_slug')
    op.create_unique_constraint(None, 'products', ['slug'])
    op.create_unique_constraint(None, 'users', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.add_column('orders', sa.Column('delivery_slug', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_delivery_slug_fkey', 'orders', 'deliveries', ['delivery_slug'], ['slug'])
    op.drop_constraint(None, 'orders', type_='unique')
    op.alter_column('orders', 'delivery_person',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('orders', 'delivery_category')
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'product_slug')
    op.drop_constraint(None, 'deliveries', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_table('order_products',
    sa.Column('order_slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_slug'], ['orders.slug'], name='order_products_order_slug_fkey'),
    sa.ForeignKeyConstraint(['product_slug'], ['products.slug'], name='order_products_product_slug_fkey'),
    sa.PrimaryKeyConstraint('order_slug', 'product_slug', name='order_products_pkey')
    )
    # ### end Alembic commands ###
